remote_theme: pmarsceill/just-the-docs

# Aux links for the upper right navigation
aux_links:
  "studyML on GitHub":
    - "//github.com/suchu3/studyML"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

google_analytics: G-N1J10H7DLE